//! Cookie → user resolution for the auth middleware.
//!
//! `authenticate` walks the three checks a protected route needs before
//! it can trust a request:
//!   1. Verify the HMAC + max-age on the session cookie value;
//!   2. Look the user up; revoked / expired rows behave as unknown;
//!   3. Best-effort stamp `last_seen_at` for the activity audit.
//!
//! The trait/Ctx pattern mirrors the other services (`critique`, `summary`)
//! so middleware tests can swap a `MockAuthDeps` without touching the DB.

use async_trait::async_trait;
use chrono::Utc;
use std::sync::Arc;

use crate::error::AppError;
use crate::models::{User, UserTier};
use crate::services::{cookies, user_store::UserSource};

/// Persistence seam consumed by [`authenticate`]. Production:
/// [`PgAuthDeps`]; tests: `MockAuthDeps` (generated by `mockall`).
#[cfg_attr(test, mockall::automock)]
#[async_trait]
pub trait AuthDeps: Send + Sync {
    async fn find_by_id(&self, id: &str) -> Result<Option<User>, AppError>;
    async fn touch_last_seen(&self, id: &str) -> Result<(), AppError>;
}

/// Request-scoped projection of the logged-in user. Lighter than `User`
/// so handlers don't have to handle every optional column. Master is
/// flagged out so admin gates can short-circuit on `is_master`.
#[derive(Debug, Clone)]
pub struct CurrentUser {
    pub id: String,
    pub label: String,
    pub tier: UserTier,
    pub is_master: bool,
}

impl CurrentUser {
    fn from_user(u: &User) -> Self {
        Self {
            id: u.id.clone(),
            label: u.label.clone(),
            tier: u.tier,
            is_master: u.is_master,
        }
    }
}

/// Verify a session cookie value and return the matching active user.
///
/// `now_unix` is read once for the max-age comparison; revocation /
/// expiry are checked against `chrono::Utc::now()` inside the same call so
/// the two clocks can't diverge across the inputs.
pub async fn authenticate(
    cookie_value: &str,
    key: &[u8],
    max_age_secs: i64,
    deps: &dyn AuthDeps,
) -> Result<CurrentUser, AppError> {
    let user_id = cookies::verify(cookie_value, key, max_age_secs, now_unix())?;
    let user = deps
        .find_by_id(&user_id)
        .await?
        .ok_or(AppError::Unauthenticated)?;
    if !user.is_active(Utc::now()) {
        return Err(AppError::Unauthenticated);
    }
    if let Err(e) = deps.touch_last_seen(&user.id).await {
        // Don't break the request — touch_last_seen is forensic, not gating.
        tracing::warn!(
            event = "auth.touch_last_seen_failed",
            user_id = %user.id,
            error = %e,
            "could not stamp last_seen_at",
        );
    }
    Ok(CurrentUser::from_user(&user))
}

fn now_unix() -> i64 {
    chrono::Utc::now().timestamp()
}

/// Production [`AuthDeps`] backed by any `UserSource`. The Arc<dyn ..>
/// indirection keeps `AppState` clonable without forcing a generic parameter
/// onto every handler that needs the middleware.
pub struct PgAuthDeps {
    pub users: Arc<dyn UserSource>,
}

#[async_trait]
impl AuthDeps for PgAuthDeps {
    async fn find_by_id(&self, id: &str) -> Result<Option<User>, AppError> {
        self.users.find_by_id(id).await
    }
    async fn touch_last_seen(&self, id: &str) -> Result<(), AppError> {
        self.users.touch_last_seen(id).await
    }
}

#[cfg(test)]
#[path = "auth_tests.rs"]
mod tests;
