//! Evaluation row read/write — Postgres `evaluations` table.
//!
//! Each `(session_id, question_id)` pair has at most one Evaluation row,
//! with attempts pushed onto a JSONB array. The orchestration handler used
//! to inline insert-vs-replace; this module owns a single
//! `INSERT ... ON CONFLICT (id) DO UPDATE` so handlers stay thin.
//!
//! Every read filters by `owner_id`; every write sets it. The handler
//! layer threads `CurrentUser::id` through.

use std::collections::{HashMap, HashSet};

use async_trait::async_trait;
use sqlx::types::Json;
use sqlx::PgPool;

use crate::error::AppError;
use crate::models::{Attempt, Evaluation, Session};

/// Persistence seam for [`load_or_create`] and [`commit_attempt`]. Production
/// impl is [`PgEvalSource`] over `&PgPool`; tests inject a mock generated by
/// `mockall::automock`.
#[cfg_attr(test, mockall::automock)]
#[async_trait]
pub trait EvalSource: Send + Sync {
    async fn find(
        &self,
        owner_id: &str,
        session_id: &str,
        question_id: &str,
    ) -> Result<Option<Evaluation>, AppError>;

    /// First attempt inserts the row; subsequent attempts replace
    /// `attempts` in place via `ON CONFLICT (id) DO UPDATE`.
    async fn upsert(&self, eval: &Evaluation) -> Result<(), AppError>;
}

/// Production impl. Owns a `&PgPool` for the duration of one request;
/// cheap to construct (the pool clones an `Arc`).
pub struct PgEvalSource<'a> {
    pub pool: &'a PgPool,
}

#[async_trait]
impl<'a> EvalSource for PgEvalSource<'a> {
    async fn find(
        &self,
        owner_id: &str,
        session_id: &str,
        question_id: &str,
    ) -> Result<Option<Evaluation>, AppError> {
        let sql = format!(
            "SELECT {EVAL_COLS} FROM evaluations
             WHERE owner_id = $1 AND session_id = $2 AND question_id = $3"
        );
        let row: Option<EvalRow> = sqlx::query_as(&sql)
            .bind(owner_id)
            .bind(session_id)
            .bind(question_id)
            .fetch_optional(self.pool)
            .await?;
        Ok(row.map(EvalRow::into_eval))
    }

    async fn upsert(&self, eval: &Evaluation) -> Result<(), AppError> {
        sqlx::query(
            r#"INSERT INTO evaluations
               (id, owner_id, session_id, company_id, question_id, question_text, attempts)
               VALUES ($1, $2, $3, $4, $5, $6, $7)
               ON CONFLICT (id) DO UPDATE SET attempts = EXCLUDED.attempts"#,
        )
        .bind(&eval.id)
        .bind(&eval.owner_id)
        .bind(&eval.session_id)
        .bind(&eval.company_id)
        .bind(&eval.question_id)
        .bind(&eval.question_text)
        .bind(Json(&eval.attempts))
        .execute(self.pool)
        .await?;
        Ok(())
    }
}

const EVAL_COLS: &str = r#"id, owner_id, session_id, company_id, question_id, question_text,
    attempts AS "attempts: Json<Vec<Attempt>>""#;

#[derive(sqlx::FromRow)]
struct EvalRow {
    id: String,
    owner_id: String,
    session_id: String,
    company_id: String,
    question_id: String,
    question_text: String,
    attempts: Json<Vec<Attempt>>,
}

impl EvalRow {
    fn into_eval(self) -> Evaluation {
        Evaluation {
            id: self.id,
            owner_id: self.owner_id,
            session_id: self.session_id,
            company_id: self.company_id,
            question_id: self.question_id,
            question_text: self.question_text,
            attempts: self.attempts.0,
        }
    }
}

// ── Pool-facing convenience wrappers ─────────────────────────────────────

/// Load the eval row for `(session, qid)` or build a fresh one. Returns the
/// row and the attempt number the next push should use.
pub async fn load_or_create(
    deps: &dyn EvalSource,
    session: &Session,
    qid: &str,
    qtext: &str,
) -> Result<(Evaluation, u32), AppError> {
    let eval = deps
        .find(&session.owner_id, &session.id, qid)
        .await?
        .unwrap_or_else(|| {
            Evaluation::new(
                session.owner_id.clone(),
                session.id.clone(),
                session.company_id.clone(),
                qid.to_string(),
                qtext.to_string(),
            )
        });
    let attempt_n = (eval.attempts.len() as u32) + 1;
    Ok((eval, attempt_n))
}

/// Push `attempt` onto `eval` and persist. First attempt inserts the row;
/// subsequent attempts replace its `attempts` array.
pub async fn commit_attempt(
    deps: &dyn EvalSource,
    mut eval: Evaluation,
    attempt: Attempt,
) -> Result<(), AppError> {
    eval.attempts.push(attempt);
    deps.upsert(&eval).await?;
    Ok(())
}

/// Load one eval row by `(session_id, eval_id)` for the attempt-audio
/// regenerate handler. Owner-scoped so a malicious id doesn't pierce out
/// of the current owner's namespace.
pub async fn load_for_attempt_edit(
    pool: &PgPool,
    owner_id: &str,
    session_id: &str,
    eval_id: &str,
) -> Result<Evaluation, AppError> {
    let sql = format!(
        "SELECT {EVAL_COLS} FROM evaluations
         WHERE owner_id = $1 AND id = $2 AND session_id = $3"
    );
    let row: Option<EvalRow> = sqlx::query_as(&sql)
        .bind(owner_id)
        .bind(eval_id)
        .bind(session_id)
        .fetch_optional(pool)
        .await?;
    row.map(EvalRow::into_eval)
        .ok_or_else(|| AppError::NotFound(format!("evaluation {eval_id}")))
}

/// All evaluations for a session, oldest-first (by `id` since the prefixed
/// random ids are not monotonic, fall back to the embedded `created_at` of
/// attempt 1; for ordering stability we use the row id which is unique).
pub async fn list_for_session(
    pool: &PgPool,
    owner_id: &str,
    session_id: &str,
) -> Result<Vec<Evaluation>, AppError> {
    let sql = format!(
        "SELECT {EVAL_COLS} FROM evaluations
         WHERE owner_id = $1 AND session_id = $2
         ORDER BY id ASC"
    );
    let rows: Vec<EvalRow> = sqlx::query_as(&sql)
        .bind(owner_id)
        .bind(session_id)
        .fetch_all(pool)
        .await?;
    Ok(rows.into_iter().map(EvalRow::into_eval).collect())
}

/// One aggregate over `evaluations` grouped by `session_id` — replaces N
/// COUNT round-trips when listing many sessions on a page.
pub async fn counts_by_session(
    pool: &PgPool,
    owner_id: &str,
    session_ids: &[&str],
) -> Result<HashMap<String, usize>, AppError> {
    if session_ids.is_empty() {
        return Ok(HashMap::new());
    }
    let owned: Vec<String> = session_ids.iter().map(|s| (*s).to_string()).collect();
    let rows = sqlx::query!(
        r#"
        SELECT session_id, COUNT(*) AS "n!"
        FROM evaluations
        WHERE owner_id = $1 AND session_id = ANY($2)
        GROUP BY session_id
        "#,
        owner_id,
        &owned,
    )
    .fetch_all(pool)
    .await?;
    Ok(rows
        .into_iter()
        .map(|r| (r.session_id, r.n as usize))
        .collect())
}

/// Set of `question_id`s already answered in `session_id`. Used by the
/// advance engine to skip questions the user has already worked.
pub async fn answered_question_ids(
    pool: &PgPool,
    owner_id: &str,
    session_id: &str,
) -> Result<HashSet<String>, AppError> {
    let rows = sqlx::query!(
        r#"SELECT question_id FROM evaluations
           WHERE owner_id = $1 AND session_id = $2"#,
        owner_id,
        session_id,
    )
    .fetch_all(pool)
    .await?;
    Ok(rows.into_iter().map(|r| r.question_id).collect())
}

#[cfg(test)]
#[path = "evaluations_tests.rs"]
mod tests;
