//! Thin OpenRouter client. One client, four shapes of call:
//! 1. Chat completion (text in, text out) — used for critique, summary
//! 2. Chat completion with web tools — used for research agent (model:online)
//! 3. Audio in (base64 input_audio) — used for STT
//! 4. /audio/speech — used for TTS
//!
//! All four go through `reqwest::Client` with the OPENROUTER_API_KEY bearer.

use std::time::Instant;

use async_trait::async_trait;
use serde::{Deserialize, Serialize};
use serde_json::Value;

use crate::error::AppError;

/// Object-safe abstraction over the four OpenRouter call shapes.
///
/// Production code holds an `Arc<dyn LlmClient>` on `AppState` (built around
/// the real `OpenRouter` struct). Tests inject a `MockLlmClient` generated by
/// `mockall::automock` to pin chat / stt / tts responses without network I/O.
#[cfg_attr(test, mockall::automock)]
#[async_trait]
pub trait LlmClient: Send + Sync {
    async fn chat(
        &self,
        model: &str,
        messages: Vec<ChatMessage>,
        force_json: bool,
    ) -> Result<String, AppError>;

    /// Like [`chat`], but enables OpenRouter's `web` plugin and returns the URLs
    /// the plugin actually fetched (parsed from `message.annotations`) so callers
    /// can distinguish ground-truth citations from anything the model claims in
    /// its body. Empty `fetched_urls` ⇒ search didn't run.
    async fn chat_with_web_search(
        &self,
        model: &str,
        messages: Vec<ChatMessage>,
        force_json: bool,
    ) -> Result<ChatWithWebSearchOut, AppError>;

    async fn stt(&self, model: &str, audio_bytes: &[u8], format: &str) -> Result<String, AppError>;

    async fn tts(
        &self,
        model: &str,
        voice: &str,
        text: &str,
        speed: Option<f32>,
        instructions: &str,
    ) -> Result<bytes::Bytes, AppError>;

    async fn list_models_raw(&self) -> Result<serde_json::Value, AppError>;

    /// Whether an API key is configured. Used by the settings pages to tell
    /// the user whether OpenRouter calls will succeed without exposing the key.
    fn configured(&self) -> bool;
}

#[async_trait]
impl LlmClient for OpenRouter {
    async fn chat(
        &self,
        model: &str,
        messages: Vec<ChatMessage>,
        force_json: bool,
    ) -> Result<String, AppError> {
        OpenRouter::chat(self, model, messages, force_json).await
    }

    async fn chat_with_web_search(
        &self,
        model: &str,
        messages: Vec<ChatMessage>,
        force_json: bool,
    ) -> Result<ChatWithWebSearchOut, AppError> {
        OpenRouter::chat_with_web_search(self, model, messages, force_json).await
    }

    async fn stt(&self, model: &str, audio_bytes: &[u8], format: &str) -> Result<String, AppError> {
        OpenRouter::stt(self, model, audio_bytes, format).await
    }

    async fn tts(
        &self,
        model: &str,
        voice: &str,
        text: &str,
        speed: Option<f32>,
        instructions: &str,
    ) -> Result<bytes::Bytes, AppError> {
        OpenRouter::tts(self, model, voice, text, speed, instructions).await
    }

    async fn list_models_raw(&self) -> Result<serde_json::Value, AppError> {
        OpenRouter::list_models_raw(self).await
    }

    fn configured(&self) -> bool {
        OpenRouter::configured(self)
    }
}

const BASE_URL: &str = "https://openrouter.ai/api/v1";

/// Default models — Phase 12 (settings) will let the user override.
pub const DEFAULT_CRITIQUE_MODEL: &str = "google/gemini-2.5-pro";
pub const DEFAULT_SUMMARY_MODEL: &str = "google/gemini-2.5-pro";
pub const DEFAULT_RESEARCH_MODEL: &str = "google/gemini-2.5-pro:online";
pub const DEFAULT_STT_MODEL: &str = "google/gemini-2.5-pro";
pub const DEFAULT_TTS_MODEL: &str = "openai/gpt-4o-mini-tts-2025-12-15";
pub const DEFAULT_TTS_VOICE: &str = "alloy";
/// Cheap fast classifier/curator. Used by `lite_model` in settings for
/// question categorization and session curation.
pub const DEFAULT_LITE_MODEL: &str = "google/gemini-2.5-flash";

#[derive(Clone)]
pub struct OpenRouter {
    http: reqwest::Client,
    api_key: String,
}

impl OpenRouter {
    pub fn new(http: reqwest::Client, api_key: String) -> Self {
        Self { http, api_key }
    }

    pub fn configured(&self) -> bool {
        !self.api_key.trim().is_empty()
    }

    fn require_key(&self) -> Result<&str, AppError> {
        if self.api_key.trim().is_empty() {
            Err(AppError::OpenRouterNotConfigured)
        } else {
            Ok(&self.api_key)
        }
    }

    /// Common headers — bearer + the referer/title pair OpenRouter expects.
    fn auth_get(&self, url: &str) -> Result<reqwest::RequestBuilder, AppError> {
        let key = self.require_key()?;
        Ok(self
            .http
            .get(url)
            .bearer_auth(key)
            .header("HTTP-Referer", "https://github.com/sahays/unslog")
            .header("X-Title", "unslog"))
    }

    fn auth_post(&self, url: &str) -> Result<reqwest::RequestBuilder, AppError> {
        let key = self.require_key()?;
        Ok(self
            .http
            .post(url)
            .bearer_auth(key)
            .header("HTTP-Referer", "https://github.com/sahays/unslog")
            .header("X-Title", "unslog"))
    }

    /// List available models from OpenRouter. Returns the raw `data` array
    /// JSON so callers can parse into their own shape.
    pub async fn list_models_raw(&self) -> Result<serde_json::Value, AppError> {
        let url = format!("{BASE_URL}/models");
        let start = Instant::now();
        let resp = self.auth_get(&url)?.send().await?;
        let duration_ms = start.elapsed().as_millis() as u64;
        if !resp.status().is_success() {
            let status = resp.status();
            let text = resp.text().await.unwrap_or_default();
            tracing::warn!(
                op = "openrouter.list_models",
                http_status = status.as_u16(),
                duration_ms,
                "openrouter /models failed",
            );
            return Err(AppError::Upstream(format!(
                "openrouter /models {status}: {text}"
            )));
        }
        let value = resp.json::<serde_json::Value>().await?;
        let count = value
            .get("data")
            .and_then(|d| d.as_array())
            .map(|a| a.len())
            .unwrap_or(0);
        tracing::info!(
            op = "openrouter.list_models",
            duration_ms,
            count,
            "openrouter /models ok",
        );
        Ok(value)
    }

    /// Plain chat completion. `messages` and `model` are caller-controlled.
    /// `force_json` adds `response_format: { type: "json_object" }`.
    /// Retries once on transient body-decode / network errors before failing
    /// — same pattern as TTS, motivated by occasional reqwest "error decoding
    /// response body" mid-stream cutoffs from OpenRouter.
    pub async fn chat(
        &self,
        model: &str,
        messages: Vec<ChatMessage>,
        force_json: bool,
    ) -> Result<String, AppError> {
        match self.chat_once(model, messages.clone(), force_json).await {
            Ok(s) => Ok(s),
            Err(first) => {
                let retryable = matches!(&first, AppError::Http(_) | AppError::Upstream(_));
                if !retryable {
                    return Err(first);
                }
                tracing::warn!(
                    op = "openrouter.chat",
                    model,
                    error = %first,
                    "first chat attempt failed, retrying once",
                );
                self.chat_once(model, messages, force_json).await
            }
        }
    }

    async fn chat_once(
        &self,
        model: &str,
        messages: Vec<ChatMessage>,
        force_json: bool,
    ) -> Result<String, AppError> {
        let prompt_chars: usize = messages.iter().map(|m| m.content.chars().count()).sum();

        let mut body = serde_json::json!({
            "model": model,
            "messages": messages,
        });
        if force_json {
            body["response_format"] = serde_json::json!({ "type": "json_object" });
        }

        let url = format!("{BASE_URL}/chat/completions");
        let start = Instant::now();
        let resp = self.auth_post(&url)?.json(&body).send().await?;
        let duration_ms = start.elapsed().as_millis() as u64;

        if !resp.status().is_success() {
            let status = resp.status();
            let text = resp.text().await.unwrap_or_default();
            tracing::warn!(
                op = "openrouter.chat",
                model,
                http_status = status.as_u16(),
                duration_ms,
                prompt_chars,
                "openrouter chat failed",
            );
            return Err(AppError::Upstream(format!(
                "openrouter chat {status}: {text}"
            )));
        }

        let parsed: ChatCompletion = resp.json().await?;
        let choice = parsed
            .choices
            .into_iter()
            .next()
            .ok_or_else(|| AppError::Upstream("openrouter returned no choices".into()))?;
        let response_chars = choice.message.content.chars().count();
        tracing::info!(
            op = "openrouter.chat",
            model,
            duration_ms,
            prompt_chars,
            response_chars,
            force_json,
            "openrouter chat ok",
        );
        Ok(choice.message.content)
    }

    /// Like [`chat`], but enables OpenRouter's `web` plugin (and appends
    /// `:online` to the model id is the caller's job — we add the plugin in
    /// the body so search runs even if the suffix was omitted). Returns the
    /// model's text plus the URLs the plugin actually fetched (from
    /// `message.annotations`). Empty `fetched_urls` is the loud signal that
    /// search did NOT run — callers should warn the user when that happens.
    /// Retries once on transient errors, same pattern as [`chat`].
    pub async fn chat_with_web_search(
        &self,
        model: &str,
        messages: Vec<ChatMessage>,
        force_json: bool,
    ) -> Result<ChatWithWebSearchOut, AppError> {
        match self
            .chat_with_web_search_once(model, messages.clone(), force_json)
            .await
        {
            Ok(o) => Ok(o),
            Err(first) => {
                let retryable = matches!(&first, AppError::Http(_) | AppError::Upstream(_));
                if !retryable {
                    return Err(first);
                }
                tracing::warn!(
                    op = "openrouter.chat_web",
                    model,
                    error = %first,
                    "first chat_with_web_search attempt failed, retrying once",
                );
                self.chat_with_web_search_once(model, messages, force_json)
                    .await
            }
        }
    }

    async fn chat_with_web_search_once(
        &self,
        model: &str,
        messages: Vec<ChatMessage>,
        force_json: bool,
    ) -> Result<ChatWithWebSearchOut, AppError> {
        let prompt_chars: usize = messages.iter().map(|m| m.content.chars().count()).sum();
        let mut body = serde_json::json!({
            "model": model,
            "messages": messages,
            "plugins": [ { "id": "web" } ],
        });
        if force_json {
            body["response_format"] = serde_json::json!({ "type": "json_object" });
        }
        let url = format!("{BASE_URL}/chat/completions");
        let start = Instant::now();
        let resp = self.auth_post(&url)?.json(&body).send().await?;
        let duration_ms = start.elapsed().as_millis() as u64;
        if !resp.status().is_success() {
            let status = resp.status();
            let text = resp.text().await.unwrap_or_default();
            tracing::warn!(
                op = "openrouter.chat_web",
                model,
                http_status = status.as_u16(),
                duration_ms,
                prompt_chars,
                "openrouter chat_with_web_search failed",
            );
            return Err(AppError::Upstream(format!(
                "openrouter chat {status}: {text}"
            )));
        }
        let parsed: ChatCompletion = resp.json().await?;
        let choice = parsed
            .choices
            .into_iter()
            .next()
            .ok_or_else(|| AppError::Upstream("openrouter returned no choices".into()))?;
        let response_chars = choice.message.content.chars().count();
        let fetched_urls = extract_fetched_urls(&choice.message.annotations);
        tracing::info!(
            op = "openrouter.chat_web",
            model,
            duration_ms,
            prompt_chars,
            response_chars,
            force_json,
            fetched_urls_n = fetched_urls.len(),
            "openrouter chat_with_web_search ok",
        );
        Ok(ChatWithWebSearchOut {
            content: choice.message.content,
            fetched_urls,
        })
    }

    /// Synthesize speech. Returns the raw audio bytes (mp3 by default).
    /// `instructions` is the natural-language voice-steering field accepted by
    /// gpt-4o-mini-tts (e.g. "Speak with a British English accent."); empty
    /// string omits it. Other TTS models silently ignore it. Retries once on
    /// transient errors.
    pub async fn tts(
        &self,
        model: &str,
        voice: &str,
        text: &str,
        speed: Option<f32>,
        instructions: &str,
    ) -> Result<bytes::Bytes, AppError> {
        match self.tts_once(model, voice, text, speed, instructions).await {
            Ok(b) => Ok(b),
            Err(first) => {
                let retryable = matches!(&first, AppError::Http(_) | AppError::Upstream(_));
                if !retryable {
                    return Err(first);
                }
                tracing::warn!(
                    op = "openrouter.tts",
                    error = %first,
                    "first TTS attempt failed, retrying once",
                );
                self.tts_once(model, voice, text, speed, instructions).await
            }
        }
    }

    async fn tts_once(
        &self,
        model: &str,
        voice: &str,
        text: &str,
        speed: Option<f32>,
        instructions: &str,
    ) -> Result<bytes::Bytes, AppError> {
        let url = format!("{BASE_URL}/audio/speech");
        let input_chars = text.chars().count();

        let mut body = serde_json::json!({
            "model": model,
            "voice": voice,
            "input": text,
            "response_format": "mp3",
        });
        if let Some(s) = speed {
            body["speed"] = serde_json::json!(s);
        }
        if !instructions.is_empty() {
            body["instructions"] = serde_json::json!(instructions);
        }

        let start = Instant::now();
        let resp = self.auth_post(&url)?.json(&body).send().await?;
        let duration_ms = start.elapsed().as_millis() as u64;

        if !resp.status().is_success() {
            let status = resp.status();
            let text = resp.text().await.unwrap_or_default();
            tracing::warn!(
                op = "openrouter.tts",
                model,
                voice,
                http_status = status.as_u16(),
                duration_ms,
                input_chars,
                "openrouter tts failed",
            );
            return Err(AppError::Upstream(format!(
                "openrouter tts {status}: {text}"
            )));
        }
        let bytes = resp.bytes().await?;
        tracing::info!(
            op = "openrouter.tts",
            model,
            voice,
            duration_ms,
            input_chars,
            audio_bytes = bytes.len(),
            "openrouter tts ok",
        );
        Ok(bytes)
    }

    /// Speech-to-text via chat-with-input_audio. Sends audio base64-encoded
    /// and asks the model to transcribe verbatim. Returns the model's text
    /// output, which we treat as the transcript after a light scrub.
    /// Retries once on transient body-decode / network errors — same pattern
    /// as `chat`/`tts`.
    pub async fn stt(
        &self,
        model: &str,
        audio_bytes: &[u8],
        format: &str,
    ) -> Result<String, AppError> {
        match self.stt_once(model, audio_bytes, format).await {
            Ok(s) => Ok(s),
            Err(first) => {
                let retryable = matches!(&first, AppError::Http(_) | AppError::Upstream(_));
                if !retryable {
                    return Err(first);
                }
                tracing::warn!(
                    op = "openrouter.stt",
                    error = %first,
                    "first STT attempt failed, retrying once",
                );
                self.stt_once(model, audio_bytes, format).await
            }
        }
    }

    async fn stt_once(
        &self,
        model: &str,
        audio_bytes: &[u8],
        format: &str,
    ) -> Result<String, AppError> {
        use base64::engine::general_purpose::STANDARD;
        use base64::Engine;
        let audio_len = audio_bytes.len();

        let b64 = STANDARD.encode(audio_bytes);
        let url = format!("{BASE_URL}/chat/completions");

        let body = serde_json::json!({
            "model": model,
            "messages": [
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "text",
                            "text": "Transcribe the following audio verbatim. Return only the transcript text — no preamble, no commentary, no quotes around it."
                        },
                        {
                            "type": "input_audio",
                            "input_audio": {
                                "data": b64,
                                "format": format,
                            }
                        }
                    ]
                }
            ],
        });

        let start = Instant::now();
        let resp = self.auth_post(&url)?.json(&body).send().await?;
        let duration_ms = start.elapsed().as_millis() as u64;

        if !resp.status().is_success() {
            let status = resp.status();
            let text = resp.text().await.unwrap_or_default();
            tracing::warn!(
                op = "openrouter.stt",
                model,
                http_status = status.as_u16(),
                duration_ms,
                audio_bytes = audio_len,
                audio_format = format,
                "openrouter stt failed",
            );
            return Err(AppError::Upstream(format!(
                "openrouter stt {status}: {text}"
            )));
        }

        let parsed: ChatCompletion = resp.json().await?;
        let choice =
            parsed.choices.into_iter().next().ok_or_else(|| {
                AppError::Upstream("openrouter returned no choices for stt".into())
            })?;
        let transcript_chars = choice.message.content.chars().count();
        tracing::info!(
            op = "openrouter.stt",
            model,
            duration_ms,
            audio_bytes = audio_len,
            audio_format = format,
            transcript_chars,
            "openrouter stt ok",
        );
        Ok(choice.message.content)
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatMessage {
    pub role: String,
    pub content: String,
}

impl ChatMessage {
    pub fn system(content: impl Into<String>) -> Self {
        Self {
            role: "system".into(),
            content: content.into(),
        }
    }
    pub fn user(content: impl Into<String>) -> Self {
        Self {
            role: "user".into(),
            content: content.into(),
        }
    }
}

#[derive(Debug, Deserialize)]
struct ChatCompletion {
    choices: Vec<ChatChoice>,
}

#[derive(Debug, Deserialize)]
struct ChatChoice {
    message: ChatChoiceMessage,
}

#[derive(Debug, Deserialize)]
struct ChatChoiceMessage {
    content: String,
    /// Present when OpenRouter ran a plugin (e.g. web search). Each entry
    /// records a URL the plugin fetched. Absent in plain chat responses.
    #[serde(default)]
    annotations: Vec<Annotation>,
}

#[derive(Debug, Deserialize)]
struct Annotation {
    #[serde(default)]
    url_citation: Option<UrlCitation>,
}

#[derive(Debug, Deserialize)]
struct UrlCitation {
    #[serde(default)]
    url: String,
}

/// Returned by [`chat_with_web_search`]. `fetched_urls` comes from OpenRouter's
/// `message.annotations` — these are the URLs the web plugin actually
/// retrieved, not anything the model produced in its body. Empty list ⇒ search
/// didn't run for this request.
#[derive(Debug, Clone)]
pub struct ChatWithWebSearchOut {
    pub content: String,
    pub fetched_urls: Vec<String>,
}

/// Flatten `message.annotations[*].url_citation.url` into a deduped, order-
/// preserving list. Skips annotations missing a citation and empty URLs.
fn extract_fetched_urls(anns: &[Annotation]) -> Vec<String> {
    use std::collections::HashSet;
    let mut seen: HashSet<String> = HashSet::new();
    let mut out: Vec<String> = Vec::with_capacity(anns.len());
    for a in anns {
        if let Some(uc) = &a.url_citation {
            if !uc.url.is_empty() && seen.insert(uc.url.clone()) {
                out.push(uc.url.clone());
            }
        }
    }
    out
}

/// Pull a fenced JSON block (``` ... ``` or ```json ... ```) out of model output,
/// or fall through to raw content. Some models wrap JSON in fences even when
/// asked not to; this normalizes that.
pub fn unwrap_fenced_json(s: &str) -> &str {
    let s = s.trim();
    if let Some(rest) = s.strip_prefix("```json") {
        if let Some(end) = rest.rfind("```") {
            return rest[..end].trim();
        }
    }
    if let Some(rest) = s.strip_prefix("```") {
        if let Some(end) = rest.rfind("```") {
            return rest[..end].trim();
        }
    }
    s
}

pub fn parse_json<T: for<'de> Deserialize<'de>>(s: &str) -> Result<T, AppError> {
    let inner = unwrap_fenced_json(s);
    let v: Value = serde_json::from_str(inner)?;
    Ok(serde_json::from_value(v)?)
}

/// Truncate a string to `n` codepoints, appending an ellipsis if cut.
/// Used by services that log a preview of failing model output.
pub fn preview(s: &str, n: usize) -> String {
    if s.chars().count() <= n {
        s.to_string()
    } else {
        s.chars().take(n).collect::<String>() + "…"
    }
}

#[cfg(test)]
#[path = "openrouter_tests.rs"]
mod tests;
