//! Research agent — produces a per-company packet.

use async_trait::async_trait;
use mongodb::Database;
use serde::Deserialize;

use crate::error::AppError;
use crate::models::company::{ResearchPacket, ResearchSource};
use crate::models::Settings;
use crate::services::openrouter::{parse_json_or_log, ChatMessage, LlmClient};
use crate::services::{prompt_escape, prompt_store, settings_store};

#[derive(Debug, Deserialize)]
struct AgentOutput {
    summary: String,
    role_jd: String,
    values_signal: String,
    #[serde(default)]
    interview_process: String,
    #[serde(default)]
    sample_questions: Vec<String>,
    #[serde(default)]
    sources: Vec<ResearchSource>,
}

/// DB-shaped dependencies of [`run`]. Production impl is [`ResearchCtx`]
/// over `&Database`; tests inject a mock generated by `mockall::automock`.
#[cfg_attr(test, mockall::automock)]
#[async_trait]
pub trait ResearchDeps: Send + Sync {
    /// Current app settings (drives model id selection).
    async fn load_settings(&self) -> Result<Settings, AppError>;

    /// Snapshotted research prompt body + the prompt-name's current
    /// version id (the latter is what gets stored on the packet).
    /// Bundled because both reads target the same prompt name and must
    /// stay consistent — re-loading the prompt twice could otherwise pick
    /// up a version bump mid-run.
    async fn load_research_prompt(&self) -> Result<ResearchPromptSnapshot, AppError>;
}

/// One snapshotted research-prompt read: the prompt body to send to the
/// model and the current version id to stamp on the resulting packet.
pub struct ResearchPromptSnapshot {
    pub body: String,
    pub current_version_id: String,
}

/// Production impl backed by a mongo `Database` reference.
pub struct ResearchCtx<'a> {
    pub db: &'a Database,
}

#[async_trait]
impl<'a> ResearchDeps for ResearchCtx<'a> {
    async fn load_settings(&self) -> Result<Settings, AppError> {
        settings_store::load(self.db).await
    }

    async fn load_research_prompt(&self) -> Result<ResearchPromptSnapshot, AppError> {
        let prompt = prompt_store::get_prompt(self.db, "research")
            .await?
            .ok_or_else(|| AppError::NotFound("research prompt".into()))?;
        let body = prompt_store::get_current_body_with_schema(self.db, "research").await?;
        Ok(ResearchPromptSnapshot {
            body,
            current_version_id: prompt.current_version_id,
        })
    }
}

pub async fn run(
    deps: &dyn ResearchDeps,
    or: &dyn LlmClient,
    company_name: &str,
    role: &str,
) -> Result<ResearchPacket, AppError> {
    let settings = deps.load_settings().await?;

    // Belt-and-suspenders: append `:online` if missing AND also send the web
    // plugin in the body. Either one alone would enable OpenRouter's web
    // search; sending both makes the intent explicit and survives setting
    // drift (e.g. user pasting a bare model id into settings).
    let model = ensure_online_suffix(&settings.research_model);

    let span = tracing::info_span!(
        "research",
        company = %company_name,
        role,
        model = %model,
    );
    let _enter = span.enter();
    let start = std::time::Instant::now();

    let snapshot = deps.load_research_prompt().await?;

    // Wrap user-typed fields in named tags so the model treats them as data,
    // not as instructions. The system prompt is updated to reinforce this.
    // HTML-escape the values so a `</company_name>` in user input can't
    // break out of the wrapper and inject directives.
    let company_name_esc = prompt_escape::for_tag(company_name);
    let role_esc = prompt_escape::for_tag(role);
    let user = format!(
        "<user_input>\n<company_name>{company_name_esc}</company_name>\n<role>{role_esc}</role>\n</user_input>\n\n\
         Produce the research packet now."
    );

    let result = or
        .chat_with_web_search(
            &model,
            vec![ChatMessage::system(snapshot.body), ChatMessage::user(user)],
            true,
        )
        .await?;
    let cleaned_content = crate::services::llm_safety::check_output("research", &result.content)?;

    let out: AgentOutput = parse_json_or_log("research", &cleaned_content)?;

    if result.fetched_urls.is_empty() {
        tracing::warn!(
            event = "research.no_web_search",
            model = %model,
            "research returned no web-search annotations — model may be answering from training data",
        );
    }

    tracing::info!(
        op = "research",
        duration_ms = start.elapsed().as_millis() as u64,
        sample_questions_n = out.sample_questions.len(),
        sources_n = out.sources.len(),
        fetched_urls_n = result.fetched_urls.len(),
        "research done",
    );

    Ok(ResearchPacket {
        summary: out.summary,
        role_jd: out.role_jd,
        values_signal: out.values_signal,
        interview_process: out.interview_process,
        sample_questions: out.sample_questions,
        sources: out.sources,
        fetched_urls: result.fetched_urls,
        research_prompt_version_id: snapshot.current_version_id,
        last_refreshed_at: chrono::Utc::now(),
    })
}

fn ensure_online_suffix(model: &str) -> String {
    if model.ends_with(":online") {
        model.to_string()
    } else {
        format!("{model}:online")
    }
}

#[cfg(test)]
#[path = "research_tests.rs"]
mod tests;
