//! End-of-session debrief.
//!
//! Loads the snapshotted summary prompt + this session's evaluations + last few
//! prior summaries for the same company, calls OpenRouter, parses JSON, and
//! persists a Summary row keyed by session_id (one summary per session).

use async_trait::async_trait;
use futures::TryStreamExt;
use mongodb::options::FindOptions;
use mongodb::Database;

use crate::error::AppError;
use crate::models::{Company, Evaluation, Session, Summary, SummaryPayload};
use crate::services::{
    openrouter::{self, ChatMessage, LlmClient},
    prompt_store,
};

/// How many prior session summaries to carry into the new summary's prompt.
const MAX_PRIOR_SUMMARIES: i64 = 3;

/// How many prior summary narratives to surface for *future* critique calls.
pub const CARRY_FORWARD_INTO_CRITIQUE: i64 = 3;

/// DB-shaped dependencies of [`generate_and_save`]. Production impl is
/// [`SummaryCtx`] over `&Database`; tests inject a mock generated by
/// `mockall::automock`.
#[cfg_attr(test, mockall::automock)]
#[async_trait]
pub trait SummaryDeps: Send + Sync {
    /// Idempotency check: any existing summary for this session.
    async fn find_existing_summary(&self, session_id: &str) -> Result<Option<Summary>, AppError>;

    /// Snapshotted summary-prompt body by version id.
    async fn get_summary_prompt_body(&self, version_id: &str) -> Result<String, AppError>;

    /// All evaluations for the session, oldest-first (`_id` ascending).
    async fn find_session_evaluations(&self, session_id: &str)
        -> Result<Vec<Evaluation>, AppError>;

    /// Recent prior summaries for `company_id`, optionally excluding the
    /// current session id (used when re-running end on a rolled-back session).
    /// Owned `Option<String>` rather than `Option<&str>` because mockall's
    /// lifetime inference doesn't elide a borrow inside `Option`.
    async fn recent_company_summaries_for_prompt(
        &self,
        company_id: &str,
        exclude_session: Option<String>,
        limit: i64,
    ) -> Result<Vec<Summary>, AppError>;

    /// Persist the freshly-built summary.
    async fn insert_summary(&self, summary: &Summary) -> Result<(), AppError>;
}

/// Production impl backed by a mongo `Database` reference.
pub struct SummaryCtx<'a> {
    pub db: &'a Database,
}

#[async_trait]
impl<'a> SummaryDeps for SummaryCtx<'a> {
    async fn find_existing_summary(&self, session_id: &str) -> Result<Option<Summary>, AppError> {
        Ok(self
            .db
            .collection::<Summary>(Summary::COLLECTION)
            .find_one(bson::doc! { "session_id": session_id })
            .await?)
    }

    async fn get_summary_prompt_body(&self, version_id: &str) -> Result<String, AppError> {
        let v = prompt_store::get_version(self.db, version_id)
            .await?
            .ok_or_else(|| AppError::NotFound("summary prompt version".into()))?;
        Ok(v.body)
    }

    async fn find_session_evaluations(
        &self,
        session_id: &str,
    ) -> Result<Vec<Evaluation>, AppError> {
        Ok(self
            .db
            .collection::<Evaluation>(Evaluation::COLLECTION)
            .find(bson::doc! { "session_id": session_id })
            .with_options(FindOptions::builder().sort(bson::doc! { "_id": 1 }).build())
            .await?
            .try_collect()
            .await?)
    }

    async fn recent_company_summaries_for_prompt(
        &self,
        company_id: &str,
        exclude_session: Option<String>,
        limit: i64,
    ) -> Result<Vec<Summary>, AppError> {
        recent_company_summaries(self.db, company_id, exclude_session.as_deref(), limit).await
    }

    async fn insert_summary(&self, summary: &Summary) -> Result<(), AppError> {
        self.db
            .collection::<Summary>(Summary::COLLECTION)
            .insert_one(summary)
            .await?;
        Ok(())
    }
}

/// Generate, persist, and return the summary for `session`. Idempotent: if a
/// summary already exists for this session, returns it unchanged.
pub async fn generate_and_save(
    deps: &dyn SummaryDeps,
    or: &dyn LlmClient,
    session: &Session,
    company: &Company,
) -> Result<Summary, AppError> {
    let span = tracing::info_span!(
        "summary",
        session_id = %session.id,
        company_id = %company.id,
        model = %session.model_snapshot.critique,
    );
    let _enter = span.enter();
    let start = std::time::Instant::now();

    if let Some(existing) = deps.find_existing_summary(&session.id).await? {
        tracing::info!(op = "summary", reused = true, "existing summary returned");
        return Ok(existing);
    }

    // Snapshotted summary prompt.
    let summary_prompt_body = deps
        .get_summary_prompt_body(&session.prompt_snapshot.summary)
        .await?;

    // This session's evaluations, ordered as they were taken.
    let evals = deps.find_session_evaluations(&session.id).await?;

    // Prior summaries for this company (excluding this session, in case we
    // re-run end on a session that was rolled back).
    let priors = deps
        .recent_company_summaries_for_prompt(
            &company.id,
            Some(session.id.clone()),
            MAX_PRIOR_SUMMARIES,
        )
        .await?;

    let user = render_user_message(company, &evals, &priors);

    let raw = or
        .chat(
            &session.model_snapshot.critique,
            vec![
                ChatMessage::system(summary_prompt_body),
                ChatMessage::user(user),
            ],
            true,
        )
        .await?;

    let payload: SummaryPayload = crate::services::openrouter::parse_json(&raw).map_err(|e| {
        tracing::warn!(error = %e, raw_preview = %openrouter::preview(&raw, 240), "summary JSON parse failed");
        AppError::Upstream(format!(
            "summary returned invalid JSON: {e} — raw: {}",
            openrouter::preview(&raw, 280)
        ))
    })?;

    let summary = Summary {
        id: uuid::Uuid::now_v7().to_string(),
        session_id: session.id.clone(),
        company_id: company.id.clone(),
        narrative: payload.narrative,
        strengths: payload.strengths,
        recurring_weaknesses: payload.recurring_weaknesses,
        blind_spots: payload.blind_spots,
        company_fit_signal: payload.company_fit_signal,
        created_at: chrono::Utc::now(),
    };
    deps.insert_summary(&summary).await?;
    tracing::info!(
        op = "summary",
        duration_ms = start.elapsed().as_millis() as u64,
        evals_n = evals.len(),
        priors_n = priors.len(),
        "summary saved",
    );

    Ok(summary)
}

/// Last `limit` summary narratives for `company_id`, newest first. Used both
/// inside the summary prompt itself (priors) and inside future critique calls
/// (carry-forward context).
pub async fn recent_company_summaries(
    db: &Database,
    company_id: &str,
    exclude_session: Option<&str>,
    limit: i64,
) -> Result<Vec<Summary>, AppError> {
    let mut filter = bson::doc! { "company_id": company_id };
    if let Some(sid) = exclude_session {
        filter.insert("session_id", bson::doc! { "$ne": sid });
    }
    let opts = FindOptions::builder()
        .sort(bson::doc! { "created_at": -1 })
        .limit(limit)
        .build();
    let cursor = db
        .collection::<Summary>(Summary::COLLECTION)
        .find(filter)
        .with_options(opts)
        .await?;
    Ok(cursor.try_collect().await?)
}

/// Lookup-by-session helper for the per-session view.
pub async fn for_session(db: &Database, session_id: &str) -> Result<Option<Summary>, AppError> {
    Ok(db
        .collection::<Summary>(Summary::COLLECTION)
        .find_one(bson::doc! { "session_id": session_id })
        .await?)
}

fn render_user_message(company: &Company, evals: &[Evaluation], priors: &[Summary]) -> String {
    let packet = company_packet(company);

    let priors_block = if priors.is_empty() {
        "(no prior session summaries for this company yet)".to_string()
    } else {
        priors
            .iter()
            .enumerate()
            .map(|(i, s)| {
                let weak = if s.recurring_weaknesses.is_empty() {
                    String::new()
                } else {
                    format!(
                        "\nrecurring_weaknesses: {}",
                        s.recurring_weaknesses.join("; ")
                    )
                };
                let blind = if s.blind_spots.is_empty() {
                    String::new()
                } else {
                    format!("\nblind_spots: {}", s.blind_spots.join("; "))
                };
                format!(
                    "Session -{} ({}):\n{}{}{}",
                    i + 1,
                    s.created_at.format("%Y-%m-%d"),
                    s.narrative,
                    weak,
                    blind,
                )
            })
            .collect::<Vec<_>>()
            .join("\n\n---\n\n")
    };

    let evals_block = if evals.is_empty() {
        "(no questions answered in this session)".to_string()
    } else {
        evals
            .iter()
            .enumerate()
            .map(|(i, e)| render_eval(i + 1, e))
            .collect::<Vec<_>>()
            .join("\n\n===\n\n")
    };

    format!(
        r#"<company_packet>
{packet}
</company_packet>

<prior_summaries>
{priors_block}
</prior_summaries>

<this_session>
{evals_block}
</this_session>

Write the debrief now. Return only the JSON object — no other text, no fences."#
    )
}

fn render_eval(idx: usize, e: &Evaluation) -> String {
    let attempts = if e.attempts.is_empty() {
        "(no attempts — question was skipped)".to_string()
    } else {
        e.attempts
            .iter()
            .map(|a| {
                let crit = match &a.critique {
                    Some(c) => {
                        let fit = c
                            .scores
                            .company_fit
                            .map(|v| format!("{v}/5"))
                            .unwrap_or_else(|| "n/a".to_string());
                        format!(
                            "\nScores: spec {}/5, role {}/5, STAR+ {}/5, pitfalls {}/5, fit {}\nCritique: {}",
                            c.scores.specificity,
                            c.scores.role_clarity,
                            c.scores.star_plus_structure,
                            c.scores.pitfalls_avoided,
                            fit,
                            c.narrative
                        )
                    }
                    None => String::new(),
                };
                format!(
                    "Attempt {}:\nAnswer: {}{}",
                    a.attempt_n, a.answer_transcript, crit
                )
            })
            .collect::<Vec<_>>()
            .join("\n\n")
    };

    format!("Q{idx}. {}\n\n{attempts}", e.question_text)
}

fn company_packet(c: &Company) -> String {
    let header = format!("Company: {}\nRole: {}", c.name, c.role);
    match &c.research_packet {
        Some(p) => format!(
            "{header}\n\nSummary:\n{}\n\nValues signal:\n{}",
            p.summary, p.values_signal
        ),
        None => header,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::models::{ModelSnapshot, PromptSnapshot, Role, SessionStatus};
    use crate::services::openrouter::MockLlmClient;
    use mockall::predicate;

    fn fixture_session() -> Session {
        Session {
            id: "sess-1".into(),
            company_id: "co-1".into(),
            role: Role::ProductManager,
            selected_company_ids: vec!["co-1".into()],
            curated_question_ids: vec![],
            focus_line: String::new(),
            started_at: chrono::Utc::now(),
            ended_at: None,
            status: SessionStatus::Ended,
            model_snapshot: ModelSnapshot {
                stt: "stt".into(),
                tts: "tts".into(),
                critique: "critique-model".into(),
                research: "research".into(),
                tts_voice: "alloy".into(),
                tts_speed: Some(1.0),
                lite: "lite".into(),
            },
            prompt_snapshot: PromptSnapshot {
                critique: "p-c".into(),
                summary: "p-s".into(),
            },
            voice_critique_enabled: false,
            current_question_id: None,
            current_question_text: None,
            current_question_audio_path: None,
        }
    }

    fn fixture_company() -> Company {
        let now = chrono::Utc::now();
        Company {
            id: "co-1".into(),
            name: "Acme".into(),
            role: "PM".into(),
            canonical_role: Role::ProductManager,
            research_packet: None,
            created_at: now,
            updated_at: now,
        }
    }

    fn existing_summary() -> Summary {
        Summary {
            id: "sum-existing".into(),
            session_id: "sess-1".into(),
            company_id: "co-1".into(),
            narrative: "already done".into(),
            strengths: vec![],
            recurring_weaknesses: vec![],
            blind_spots: vec![],
            company_fit_signal: String::new(),
            created_at: chrono::Utc::now(),
        }
    }

    #[tokio::test]
    async fn case_generate_skips_when_already_present() {
        // Idempotency: an existing summary short-circuits the LLM and the
        // insert. Pin those .times(0) call counts.
        let mut deps = MockSummaryDeps::new();
        deps.expect_find_existing_summary()
            .with(predicate::eq("sess-1"))
            .times(1)
            .returning(|_| Ok(Some(existing_summary())));
        deps.expect_insert_summary().times(0);

        let mut llm = MockLlmClient::new();
        llm.expect_chat().times(0);

        let session = fixture_session();
        let company = fixture_company();
        let out = generate_and_save(&deps, &llm, &session, &company)
            .await
            .expect("ok");
        assert_eq!(out.id, "sum-existing");
        assert_eq!(out.narrative, "already done");
    }

    #[tokio::test]
    async fn case_generate_calls_llm_when_absent() {
        let mut deps = MockSummaryDeps::new();
        deps.expect_find_existing_summary()
            .times(1)
            .returning(|_| Ok(None));
        deps.expect_get_summary_prompt_body()
            .with(predicate::eq("p-s"))
            .times(1)
            .returning(|_| Ok("be a coach".into()));
        deps.expect_find_session_evaluations()
            .times(1)
            .returning(|_| Ok(vec![]));
        deps.expect_recent_company_summaries_for_prompt()
            .times(1)
            .returning(|_, _, _| Ok(vec![]));
        deps.expect_insert_summary().times(1).returning(|_| Ok(()));

        let mut llm = MockLlmClient::new();
        llm.expect_chat().times(1).returning(|_, _, _| {
            Ok(r#"{
  "narrative": "did fine",
  "strengths": ["clear stories"],
  "recurring_weaknesses": [],
  "blind_spots": [],
  "company_fit_signal": "neutral"
}"#
            .to_string())
        });

        let session = fixture_session();
        let company = fixture_company();
        let out = generate_and_save(&deps, &llm, &session, &company)
            .await
            .expect("ok");
        assert_eq!(out.session_id, "sess-1");
        assert_eq!(out.narrative, "did fine");
        assert_eq!(out.strengths, vec!["clear stories".to_string()]);
    }
}
