//! End-of-session debrief.
//!
//! Loads the snapshotted summary prompt + this session's evaluations + last few
//! prior summaries for the same company, calls OpenRouter, parses JSON, and
//! persists a Summary row keyed by session_id (one summary per session).
//!
//! Pool reads/writes live in [`mod store`]; the user-message render lives in
//! [`mod prompt`]. This file owns the trait + orchestration only.

mod prompt;
mod store;

pub use store::{by_session_ids, for_session};

use async_trait::async_trait;
use sqlx::PgPool;

use crate::error::AppError;
use crate::models::{Company, Evaluation, Session, Summary, SummaryPayload};
use crate::services::{
    evaluations,
    openrouter::{ChatMessage, LlmClient},
    prompt_store,
};

/// How many prior session summaries to carry into the new summary's prompt.
const MAX_PRIOR_SUMMARIES: i64 = 3;

/// How many prior summary narratives to surface for *future* critique calls.
pub const CARRY_FORWARD_INTO_CRITIQUE: i64 = 3;

/// DB-shaped dependencies of [`generate_and_save`]. Production impl is
/// [`SummaryCtx`] over `&PgPool`; tests inject a mock generated by
/// `mockall::automock`.
#[cfg_attr(test, mockall::automock)]
#[async_trait]
pub trait SummaryDeps: Send + Sync {
    async fn find_existing_summary(
        &self,
        owner_id: &str,
        session_id: &str,
    ) -> Result<Option<Summary>, AppError>;
    async fn get_summary_prompt_body(&self, version_id: &str) -> Result<String, AppError>;
    async fn find_session_evaluations(
        &self,
        owner_id: &str,
        session_id: &str,
    ) -> Result<Vec<Evaluation>, AppError>;
    /// `exclude_session` owned because mockall can't elide a borrow inside Option.
    async fn recent_company_summaries_for_prompt(
        &self,
        owner_id: &str,
        company_id: &str,
        exclude_session: Option<String>,
        limit: i64,
    ) -> Result<Vec<Summary>, AppError>;
    async fn insert_summary(&self, summary: &Summary) -> Result<(), AppError>;
}

/// Production impl backed by a Postgres pool.
pub struct SummaryCtx<'a> {
    pub pool: &'a PgPool,
}

#[async_trait]
impl<'a> SummaryDeps for SummaryCtx<'a> {
    async fn find_existing_summary(
        &self,
        owner_id: &str,
        session_id: &str,
    ) -> Result<Option<Summary>, AppError> {
        store::for_session(self.pool, owner_id, session_id).await
    }

    async fn get_summary_prompt_body(&self, version_id: &str) -> Result<String, AppError> {
        let v = prompt_store::get_version(self.pool, version_id)
            .await?
            .ok_or_else(|| AppError::NotFound("summary prompt version".into()))?;
        Ok(v.body)
    }

    async fn find_session_evaluations(
        &self,
        owner_id: &str,
        session_id: &str,
    ) -> Result<Vec<Evaluation>, AppError> {
        evaluations::list_for_session(self.pool, owner_id, session_id).await
    }

    async fn recent_company_summaries_for_prompt(
        &self,
        owner_id: &str,
        company_id: &str,
        exclude_session: Option<String>,
        limit: i64,
    ) -> Result<Vec<Summary>, AppError> {
        store::recent_for_company(
            self.pool,
            owner_id,
            company_id,
            exclude_session.as_deref(),
            limit,
        )
        .await
    }

    async fn insert_summary(&self, summary: &Summary) -> Result<(), AppError> {
        store::insert(self.pool, summary).await
    }
}

/// Generate, persist, and return the summary for `session`. Idempotent.
pub async fn generate_and_save(
    deps: &dyn SummaryDeps,
    or: &dyn LlmClient,
    session: &Session,
    company: &Company,
) -> Result<Summary, AppError> {
    let span = tracing::info_span!(
        "summary",
        session_id = %session.id,
        company_id = %company.id,
        model = %session.model_snapshot.critique,
    );
    let _enter = span.enter();
    let start = std::time::Instant::now();

    if let Some(existing) = deps
        .find_existing_summary(&session.owner_id, &session.id)
        .await?
    {
        tracing::info!(
            event = "summary.reused",
            session_id = %session.id,
            "existing summary returned"
        );
        return Ok(existing);
    }

    let body = prompt_store::with_schema(
        "summary",
        deps.get_summary_prompt_body(&session.prompt_snapshot.summary)
            .await?,
    );
    let evals = deps
        .find_session_evaluations(&session.owner_id, &session.id)
        .await?;
    let priors = deps
        .recent_company_summaries_for_prompt(
            &session.owner_id,
            &company.id,
            Some(session.id.clone()),
            MAX_PRIOR_SUMMARIES,
        )
        .await?;

    let payload = call_llm(or, session, body, company, &evals, &priors).await?;
    let summary = build_summary(session, company, payload);
    deps.insert_summary(&summary).await?;

    tracing::info!(
        event = "summary.saved",
        session_id = %session.id,
        duration_ms = start.elapsed().as_millis() as u64,
        evals_n = evals.len(),
        priors_n = priors.len(),
        "summary saved",
    );
    Ok(summary)
}

async fn call_llm(
    or: &dyn LlmClient,
    session: &Session,
    system_body: String,
    company: &Company,
    evals: &[Evaluation],
    priors: &[Summary],
) -> Result<SummaryPayload, AppError> {
    let user = prompt::render_user_message(company, evals, priors);
    let raw = or
        .chat(
            &session.model_snapshot.critique,
            vec![ChatMessage::system(system_body), ChatMessage::user(user)],
            true,
        )
        .await?;
    let raw = crate::services::llm_safety::check_output("summary", &raw)?;
    crate::services::openrouter::parse_json_or_log("summary", &raw)
}

fn build_summary(session: &Session, company: &Company, payload: SummaryPayload) -> Summary {
    Summary {
        id: Summary::new_id(),
        owner_id: session.owner_id.clone(),
        session_id: session.id.clone(),
        company_id: company.id.clone(),
        narrative: payload.narrative,
        strengths: payload.strengths,
        recurring_weaknesses: payload.recurring_weaknesses,
        blind_spots: payload.blind_spots,
        company_fit_signal: payload.company_fit_signal,
        created_at: chrono::Utc::now(),
    }
}

/// Backward-compat free fn used by `routes::sessions::answer`. Defers to
/// the store module.
pub async fn recent_company_summaries(
    pool: &PgPool,
    owner_id: &str,
    company_id: &str,
    exclude_session: Option<&str>,
    limit: i64,
) -> Result<Vec<Summary>, AppError> {
    store::recent_for_company(pool, owner_id, company_id, exclude_session, limit).await
}

#[cfg(test)]
#[path = "summary_tests.rs"]
mod tests;
