//! Cap-check + rate-limit gate.
//!
//! Pure-logic surface: the trait owns the DB read and the per-tier policy
//! lookup; this module decides whether the request fits in the user's
//! remaining budget. Returns the snapshotted `UsageWindow` on success so
//! the caller can populate the sidebar bar in the same code path.

use async_trait::async_trait;
use chrono::{DateTime, Duration, Utc};

use crate::error::AppError;
use crate::models::UsageWindow;
use crate::services::auth::CurrentUser;

/// One audit row's worth of input. Bundled so the trait method signature
/// fits clippy's 7-arg budget. Owned (vs borrowed) because `mockall` can't
/// generate mocks for trait methods with anonymous lifetimes in struct
/// parameters; the allocation cost is dwarfed by the SQL round-trip.
#[derive(Debug, Clone)]
pub struct AppendRow {
    pub user_id: String,
    pub method: String,
    pub path: String,
    pub status: i16,
    pub duration_ms: i32,
    pub kind: String,
    pub cost_units: u32,
}

/// Persistence + policy seam consumed by [`check_or_block`] and the
/// fire-and-forget log appender. Production: [`super::super::request_log_store::PgMeteringDeps`];
/// tests: `MockMeteringDeps` (generated by `mockall`).
#[cfg_attr(test, mockall::automock)]
#[async_trait]
pub trait MeteringDeps: Send + Sync {
    /// Sum `cost_units` for `user_id` over `[since, now]`.
    async fn sum_units_window(&self, user_id: &str, since: DateTime<Utc>) -> Result<u64, AppError>;
    /// Per-tier daily cap. `None` = no cap (master / unlimited).
    fn tier_cap_for(&self, user: &CurrentUser) -> Option<u32>;
    /// Append a single audit row. Called from the fire-and-forget log task.
    async fn append(&self, row: AppendRow) -> Result<(), AppError>;
}

/// Rolling 24-hour window. Trade-off: cheaper than calendar-day partitioning
/// and harder to game ("midnight reset") than a fixed bucket.
pub const WINDOW: Duration = Duration::hours(24);

/// Verify the request fits in the user's remaining budget. Returns the
/// usage snapshot (which the rendering layer can publish into a task-local
/// for the sidebar bar). Returns [`AppError::RateLimited`] when over cap.
pub async fn check_or_block(
    deps: &dyn MeteringDeps,
    user: &CurrentUser,
    weight: u32,
) -> Result<UsageWindow, AppError> {
    let Some(cap) = deps.tier_cap_for(user) else {
        // Master / unlimited path — never blocked.
        let used = deps
            .sum_units_window(&user.id, window_start(Utc::now()))
            .await
            .unwrap_or(0);
        return Ok(UsageWindow {
            used,
            cap: u64::MAX,
        });
    };
    let used = deps
        .sum_units_window(&user.id, window_start(Utc::now()))
        .await?;
    if used.saturating_add(weight as u64) > cap as u64 {
        tracing::warn!(
            event = "meter.cap_block",
            user_id = %user.id,
            tier = %user.tier.as_str(),
            used = used,
            cap = cap,
            weight = weight,
            "request blocked at cap",
        );
        return Err(AppError::RateLimited {
            used: used.min(u32::MAX as u64) as u32,
            cap,
        });
    }
    Ok(UsageWindow {
        used,
        cap: cap as u64,
    })
}

/// Snapshot the current window without enforcing a charge — used by the
/// sidebar usage bar after auth, so master / over-cap users still see a
/// consistent number. Failures degrade to "0 used".
pub async fn current_window(deps: &dyn MeteringDeps, user: &CurrentUser) -> UsageWindow {
    let used = deps
        .sum_units_window(&user.id, window_start(Utc::now()))
        .await
        .unwrap_or(0);
    let cap = deps
        .tier_cap_for(user)
        .map(|c| c as u64)
        .unwrap_or(u64::MAX);
    UsageWindow { used, cap }
}

fn window_start(now: DateTime<Utc>) -> DateTime<Utc> {
    now - WINDOW
}

#[cfg(test)]
#[path = "cap_tests.rs"]
mod tests;
