//! Thin OpenRouter client. One client, four shapes of call:
//! 1. Chat completion (text in, text out) — used for critique, summary
//! 2. Chat completion with web tools — used for research agent (model:online)
//! 3. Audio in (base64 input_audio) — used for STT
//! 4. /audio/speech — used for TTS
//!
//! All four go through `reqwest::Client` with the OPENROUTER_API_KEY bearer.
//!
//! The four call shapes live in sibling modules (`chat`, `stt`, `tts`) plus
//! the JSON post-processing helpers in `json`. This file owns the
//! [`LlmClient`] trait, the [`OpenRouter`] struct, the auth/header helpers,
//! the `retry_once` wrapper, and the small set of public types every caller
//! touches (`ChatMessage`, `ChatWithWebSearchOut`, the default model
//! constants).

use std::future::Future;

use async_trait::async_trait;
use serde::{Deserialize, Serialize};

use crate::error::AppError;

mod chat;
mod json;
mod list_models;
mod stt;
mod tts;

pub use chat::ChatWithWebSearchOut;
pub use json::{parse_json, parse_json_or_log, unwrap_fenced_json};

/// Errors we'll retry once. Transient classifier shared by every
/// retry_once-wrapped call. Reqwest body-decode + upstream-error responses
/// are the two flakes we've observed on OpenRouter — anything else
/// (`BadRequest`, `OpenRouterNotConfigured`, `Mongo`, etc.) is deterministic
/// and a retry would just burn tokens.
pub(crate) fn is_transient(e: &AppError) -> bool {
    matches!(e, AppError::Http(_) | AppError::Upstream(_))
}

/// Invoke `f`, retry once on transient errors. Used by every outbound
/// OpenRouter call (chat / chat_web / tts / stt) — the chat/audio APIs
/// occasionally return mid-stream body-decode errors, and the cheapest
/// available mitigation is one fresh attempt.
pub(crate) async fn retry_once<T, F, Fut>(op: &'static str, mut f: F) -> Result<T, AppError>
where
    F: FnMut() -> Fut,
    Fut: Future<Output = Result<T, AppError>>,
{
    match f().await {
        Ok(v) => Ok(v),
        Err(first) => {
            if !is_transient(&first) {
                return Err(first);
            }
            // The full Display of `Upstream` includes the upstream status;
            // bound it with `preview` so a future variant that ends up
            // wrapping a large body can't flood the log line.
            let first_str = first.to_string();
            tracing::warn!(
                op = %op,
                error_preview = %crate::services::redact::preview(&first_str, 240),
                "first attempt failed, retrying once",
            );
            f().await
        }
    }
}

/// Object-safe abstraction over the four OpenRouter call shapes.
///
/// Production code holds an `Arc<dyn LlmClient>` on `AppState` (built around
/// the real `OpenRouter` struct). Tests inject a `MockLlmClient` generated by
/// `mockall::automock` to pin chat / stt / tts responses without network I/O.
#[cfg_attr(test, mockall::automock)]
#[async_trait]
pub trait LlmClient: Send + Sync {
    async fn chat(
        &self,
        model: &str,
        messages: Vec<ChatMessage>,
        force_json: bool,
    ) -> Result<String, AppError>;

    /// Like [`chat`], but enables OpenRouter's `web` plugin and returns the URLs
    /// the plugin actually fetched (parsed from `message.annotations`) so callers
    /// can distinguish ground-truth citations from anything the model claims in
    /// its body. Empty `fetched_urls` ⇒ search didn't run.
    async fn chat_with_web_search(
        &self,
        model: &str,
        messages: Vec<ChatMessage>,
        force_json: bool,
    ) -> Result<ChatWithWebSearchOut, AppError>;

    async fn stt(&self, model: &str, audio_bytes: &[u8], format: &str) -> Result<String, AppError>;

    async fn tts(
        &self,
        model: &str,
        voice: &str,
        text: &str,
        speed: Option<f32>,
        instructions: &str,
    ) -> Result<bytes::Bytes, AppError>;

    async fn list_models_raw(&self) -> Result<serde_json::Value, AppError>;

    /// Whether an API key is configured. Used by the settings pages to tell
    /// the user whether OpenRouter calls will succeed without exposing the key.
    fn configured(&self) -> bool;
}

#[async_trait]
impl LlmClient for OpenRouter {
    async fn chat(
        &self,
        model: &str,
        messages: Vec<ChatMessage>,
        force_json: bool,
    ) -> Result<String, AppError> {
        OpenRouter::chat(self, model, messages, force_json).await
    }

    async fn chat_with_web_search(
        &self,
        model: &str,
        messages: Vec<ChatMessage>,
        force_json: bool,
    ) -> Result<ChatWithWebSearchOut, AppError> {
        OpenRouter::chat_with_web_search(self, model, messages, force_json).await
    }

    async fn stt(&self, model: &str, audio_bytes: &[u8], format: &str) -> Result<String, AppError> {
        OpenRouter::stt(self, model, audio_bytes, format).await
    }

    async fn tts(
        &self,
        model: &str,
        voice: &str,
        text: &str,
        speed: Option<f32>,
        instructions: &str,
    ) -> Result<bytes::Bytes, AppError> {
        OpenRouter::tts(self, model, voice, text, speed, instructions).await
    }

    async fn list_models_raw(&self) -> Result<serde_json::Value, AppError> {
        OpenRouter::list_models_raw(self).await
    }

    fn configured(&self) -> bool {
        OpenRouter::configured(self)
    }
}

pub(crate) const BASE_URL: &str = "https://openrouter.ai/api/v1";

/// Default models — Phase 12 (settings) will let the user override.
pub const DEFAULT_CRITIQUE_MODEL: &str = "google/gemini-2.5-pro";
pub const DEFAULT_SUMMARY_MODEL: &str = "google/gemini-2.5-pro";
pub const DEFAULT_RESEARCH_MODEL: &str = "google/gemini-2.5-pro:online";
pub const DEFAULT_STT_MODEL: &str = "google/gemini-2.5-pro";
pub const DEFAULT_TTS_MODEL: &str = "openai/gpt-4o-mini-tts-2025-12-15";
pub const DEFAULT_TTS_VOICE: &str = "alloy";
/// Cheap fast classifier/curator. Used by `lite_model` in settings for
/// question categorization and session curation.
pub const DEFAULT_LITE_MODEL: &str = "google/gemini-2.5-flash";

#[derive(Clone)]
pub struct OpenRouter {
    http: reqwest::Client,
    api_key: String,
    /// Optional value to send as `HTTP-Referer`. `None` = omit the header
    /// (default). Set via `AppConfig::referer` / `UNSLOG_REFERER`.
    referer: Option<String>,
}

impl OpenRouter {
    pub fn new(http: reqwest::Client, api_key: String, referer: Option<String>) -> Self {
        Self {
            http,
            api_key,
            referer,
        }
    }

    pub fn configured(&self) -> bool {
        !self.api_key.trim().is_empty()
    }

    fn require_key(&self) -> Result<&str, AppError> {
        if self.api_key.trim().is_empty() {
            Err(AppError::OpenRouterNotConfigured)
        } else {
            Ok(&self.api_key)
        }
    }

    /// Attach the standard attribution headers OpenRouter expects.
    /// `HTTP-Referer` is only sent when [`AppConfig::referer`] is configured,
    /// so the default install doesn't leak a hard-coded personal repo URL.
    fn with_attribution(&self, mut req: reqwest::RequestBuilder) -> reqwest::RequestBuilder {
        if let Some(referer) = self.referer.as_deref() {
            req = req.header("HTTP-Referer", referer);
        }
        req.header("X-Title", "unslog")
    }

    /// Common headers — bearer + (optional) referer + title.
    pub(crate) fn auth_get(&self, url: &str) -> Result<reqwest::RequestBuilder, AppError> {
        let key = self.require_key()?;
        Ok(self.with_attribution(self.http.get(url).bearer_auth(key)))
    }

    pub(crate) fn auth_post(&self, url: &str) -> Result<reqwest::RequestBuilder, AppError> {
        let key = self.require_key()?;
        Ok(self.with_attribution(self.http.post(url).bearer_auth(key)))
    }

    // list_models_raw lives in list_models.rs.
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatMessage {
    pub role: String,
    pub content: String,
}

impl ChatMessage {
    pub fn system(content: impl Into<String>) -> Self {
        Self {
            role: "system".into(),
            content: content.into(),
        }
    }
    pub fn user(content: impl Into<String>) -> Self {
        Self {
            role: "user".into(),
            content: content.into(),
        }
    }
}

/// Chat-completion response shape used by `chat`, `chat_with_web_search`,
/// and `stt` (since STT goes via the chat-completions endpoint with an
/// `input_audio` content block).
#[derive(Debug, Deserialize)]
pub(crate) struct ChatCompletion {
    pub(crate) choices: Vec<ChatChoice>,
}

#[derive(Debug, Deserialize)]
pub(crate) struct ChatChoice {
    pub(crate) message: ChatChoiceMessage,
}

#[derive(Debug, Deserialize)]
pub(crate) struct ChatChoiceMessage {
    pub(crate) content: String,
    /// Present when OpenRouter ran a plugin (e.g. web search). Each entry
    /// records a URL the plugin fetched. Absent in plain chat responses.
    #[serde(default)]
    pub(crate) annotations: Vec<chat::Annotation>,
}

#[cfg(test)]
#[path = "../openrouter_tests.rs"]
mod tests;
