use serde::{Deserialize, Serialize};

use crate::models::Role;

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum QuestionSource {
    /// Pasted in by the user.
    Uploaded,
    /// Generated by the research agent during company create / refresh.
    Agent,
    /// Seeded from the canonical pitch catalog (`/pitches`). One Question
    /// per pitch slug, role-only (no company), so every Practice session
    /// can draw it.
    Pitch,
}

/// A single behavioral-interview question. Backed by the Postgres
/// `questions` table after Phase A Step 6; the importer still
/// deserializes legacy Mongo docs via the `_id` rename. Optional
/// `company_id` lets role-only questions exist alongside company-tagged
/// ones — the curator pools across both.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Question {
    #[serde(rename = "_id")]
    pub id: String,
    /// Per-user; set by the calling handler from `CurrentUser::id`.
    #[serde(default)]
    pub owner_id: String,
    pub text: String,
    pub source: QuestionSource,
    /// Canonical role this question belongs to. Always present.
    #[serde(default = "default_role")]
    pub role: Role,
    /// Canonical category IDs (from `Category::COLLECTION`). 0–N OK.
    /// JSONB on the Postgres side; a GIN index supports `@>` filters.
    #[serde(default)]
    pub categories: Vec<String>,
    /// Source company. `None` = role-only question, applies to any company
    /// of this role. The curator includes both company-tagged and role-only
    /// questions in its pool.
    #[serde(default)]
    pub company_id: Option<String>,
    #[serde(with = "crate::models::datetime_compat::required")]
    pub added_at: chrono::DateTime<chrono::Utc>,
}

fn default_role() -> Role {
    Role::SolutionsArchitect
}

impl Question {
    /// Legacy Mongo collection name. Still referenced by the one-shot
    /// importer — removed in the final sub-phase that drops `mongodb`.
    pub const COLLECTION: &'static str = "questions";

    pub fn new(
        owner_id: String,
        text: String,
        source: QuestionSource,
        role: Role,
        categories: Vec<String>,
        company_id: Option<String>,
    ) -> Self {
        Self {
            id: crate::services::id_gen::new(crate::services::id_gen::Kind::Question),
            owner_id,
            text,
            source,
            role,
            categories,
            company_id,
            added_at: chrono::Utc::now(),
        }
    }

    /// Template helper — Askama can't run closure expressions, so we expose
    /// "is this question tagged with category X?" as a method.
    pub fn has_category(&self, id: &str) -> bool {
        self.categories.iter().any(|c| c == id)
    }
}
