use serde::{Deserialize, Serialize};

use crate::models::Role;

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum QuestionSource {
    /// Pasted in by the user.
    Uploaded,
    /// Generated by the research agent during company create / refresh.
    Agent,
    /// Seeded from the canonical pitch catalog (`/pitches`). One Question
    /// per pitch slug, role-only (no company), so every Practice session
    /// can draw it.
    Pitch,
}

/// A single behavioral-interview question. Top-level MongoDB document
/// (collection: `questions`). Optional `company_id` lets role-only questions
/// exist alongside company-tagged ones — the curator pools across both.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Question {
    #[serde(rename = "_id")]
    pub id: String,
    pub text: String,
    pub source: QuestionSource,
    /// Canonical role this question belongs to. Always present.
    #[serde(default = "default_role")]
    pub role: Role,
    /// Canonical category IDs (from `Category::COLLECTION`). 0–N OK.
    #[serde(default)]
    pub categories: Vec<String>,
    /// Source company. `None` = role-only question, applies to any company
    /// of this role. The curator includes both company-tagged and role-only
    /// questions in its pool.
    #[serde(default)]
    pub company_id: Option<String>,
    #[serde(with = "crate::models::datetime_compat::required")]
    pub added_at: chrono::DateTime<chrono::Utc>,
}

fn default_role() -> Role {
    Role::SolutionsArchitect
}

impl Question {
    pub const COLLECTION: &'static str = "questions";

    pub fn new(
        text: String,
        source: QuestionSource,
        role: Role,
        categories: Vec<String>,
        company_id: Option<String>,
    ) -> Self {
        Self {
            id: uuid::Uuid::now_v7().to_string(),
            text,
            source,
            role,
            categories,
            company_id,
            added_at: chrono::Utc::now(),
        }
    }

    /// Template helper — Askama can't run closure expressions, so we expose
    /// "is this question tagged with category X?" as a method.
    pub fn has_category(&self, id: &str) -> bool {
        self.categories.iter().any(|c| c == id)
    }
}
