//! Story Builder — competency-tagged STAR+ stories driven by AI-led probing.
//!
//! A `Story` is the persistent shell: chosen competency, embedded chat history,
//! and a pointer to the current `StoryVersion`. `StoryVersion` is an immutable
//! snapshot of the bullet-form story at one point in time. Chat is the source
//! of truth; bullets are the index.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum StoryStatus {
    InProgress,
    Complete,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ChatRole {
    User,
    Assistant,
}

impl ChatRole {
    pub fn as_str(self) -> &'static str {
        match self {
            ChatRole::User => "user",
            ChatRole::Assistant => "assistant",
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatTurn {
    pub role: ChatRole,
    pub content: String,
    #[serde(with = "crate::models::datetime_compat::required")]
    pub ts: chrono::DateTime<chrono::Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Story {
    #[serde(rename = "_id")]
    pub id: String,
    /// FK → `categories._id`. The competency this story is being built against.
    pub competency_id: String,
    pub status: StoryStatus,
    /// FK → `story_versions._id` of the latest locked-in version. `None` until
    /// the user clicks Generate the first time.
    #[serde(default)]
    pub current_version_id: Option<String>,
    /// Embedded chat — monotonic, append-only. Worst-case ~50 turns × ~250
    /// chars ≈ 12 KB; comfortably under the 16 MB doc limit.
    #[serde(default)]
    pub chat: Vec<ChatTurn>,
    #[serde(with = "crate::models::datetime_compat::required")]
    pub created_at: chrono::DateTime<chrono::Utc>,
    #[serde(with = "crate::models::datetime_compat::required")]
    pub updated_at: chrono::DateTime<chrono::Utc>,
}

impl Story {
    pub const COLLECTION: &'static str = "stories";
}

/// STAR+ bullets per section. Each list is 3–6 short bullets in the
/// candidate's voice, generated by the summarize prompt.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct StoryBody {
    #[serde(default)]
    pub situation: Vec<String>,
    #[serde(default)]
    pub task: Vec<String>,
    #[serde(default)]
    pub action: Vec<String>,
    #[serde(default)]
    pub result: Vec<String>,
    /// The "+" of STAR+ — reflection / what was learned / how it changed
    /// the candidate's approach.
    #[serde(default)]
    pub reflection: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StoryVersion {
    #[serde(rename = "_id")]
    pub id: String,
    pub story_id: String,
    /// Monotonic per story: 1, 2, 3, …
    pub version_n: u32,
    pub body: StoryBody,
    #[serde(with = "crate::models::datetime_compat::required")]
    pub created_at: chrono::DateTime<chrono::Utc>,
}

impl StoryVersion {
    pub const COLLECTION: &'static str = "story_versions";
}
